/**
 * Edelstein1996_EPSP_AChEvent.c
 * This is an autogenerated model file, generated by sbml2rdme with intended use for
 * URDME 1.2 or later using Comsol mutliphysics 4.2 or later.
 * Please be sure to validate the generated code, especially if sbml2rdme produced any warnings.
**/

#include <stdlib.h>
#include "propensities.h"


/* SPECIES */
enum {BLL=0,IL,AL,A,BL,B,DLL,D,ILL,DL,I,ALL};


/* COMPARTMENTS */
/*
  The given model does not contains enough different compartments (1 are detected)
  for it to be neccessary to add subdomain support.
*/
const double NR = 17; /* Number of reactions */
const double kf_10 = 19.85;
const double kf_11 = 20.0;
const double kf_12 = 3000.0;
const double kf_13 = 1500.0;
const double kf_14 = 0.05;
const double kf_15 = 0.05;
const double kf_16 = 0.05;
const double kf_8 = 1500.0;
const double kf_9 = 19.7;
const double kf_2 = 30000.0;
const double kf_3 = 3000.0;
const double kf_0 = 3000.0;
const double kf_1 = 1500.0;
const double kf_6 = 130.0;
const double kf_7 = 3000.0;
const double kf_4 = 1500.0;
const double kf_5 = 0.54;
const double kr_14 = 0.0012;
const double kr_15 = 0.0012;
const double kr_16 = 0.0012;
const double kr_10 = 1.74;
const double kr_11 = 0.81;
const double kr_12 = 4.0;
const double kr_13 = 8.0;
const double kr_6 = 2740.0;
const double kr_7 = 4.0;
const double kr_4 = 17.28;
const double kr_5 = 10800.0;
const double kr_2 = 700.0;
const double kr_3 = 8.64;
const double kr_0 = 8000.0;
const double kr_1 = 16000.0;
const double t2 = 20.0;
const double kr_8 = 8.0;
const double kr_9 = 3.74;

/* Propensity function 1*/
double React0(const int *x, double t, double vol, const double *data, int sd)
{
  return vol * (kf_0 * x[B] - kr_0 * x[BL]);
}

/* Propensity function 2*/
double React1(const int *x, double t, double vol, const double *data, int sd)
{
  return vol * (kf_1 * x[BL] - kr_1 * x[BLL]);
}

/* Propensity function 3*/
double React2(const int *x, double t, double vol, const double *data, int sd)
{
  return vol * (kf_2 * x[BLL] - kr_2 * x[ALL]);
}

/* Propensity function 4*/
double React3(const int *x, double t, double vol, const double *data, int sd)
{
  return vol * (kf_3 * x[A] - kr_3 * x[AL]);
}

/* Propensity function 5*/
double React4(const int *x, double t, double vol, const double *data, int sd)
{
  return vol * (kf_4 * x[AL] - kr_4 * x[ALL]);
}

/* Propensity function 6*/
double React5(const int *x, double t, double vol, const double *data, int sd)
{
  return vol * (kf_5 * x[B] - kr_5 * x[A]);
}

/* Propensity function 7*/
double React6(const int *x, double t, double vol, const double *data, int sd)
{
  return vol * (kf_6 * x[BL] - kr_6 * x[AL]);
}

/* Propensity function 8*/
double React7(const int *x, double t, double vol, const double *data, int sd)
{
  return vol * (kf_7 * x[I] - kr_7 * x[IL]);
}

/* Propensity function 9*/
double React8(const int *x, double t, double vol, const double *data, int sd)
{
  return vol * (kf_8 * x[IL] - kr_8 * x[ILL]);
}

/* Propensity function 10*/
double React9(const int *x, double t, double vol, const double *data, int sd)
{
  return vol * (kf_9 * x[A] - kr_9 * x[I]);
}

/* Propensity function 11*/
double React10(const int *x, double t, double vol, const double *data, int sd)
{
  return vol * (kf_10 * x[AL] - kr_10 * x[IL]);
}

/* Propensity function 12*/
double React11(const int *x, double t, double vol, const double *data, int sd)
{
  return vol * (kf_11 * x[ALL] - kr_11 * x[ILL]);
}

/* Propensity function 13*/
double React12(const int *x, double t, double vol, const double *data, int sd)
{
  return vol * (kf_12 * x[D] - kr_12 * x[DL]);
}

/* Propensity function 14*/
double React13(const int *x, double t, double vol, const double *data, int sd)
{
  return vol * (kf_13 * x[DL] - kr_13 * x[DLL]);
}

/* Propensity function 15*/
double React14(const int *x, double t, double vol, const double *data, int sd)
{
  return vol * (kf_14 * x[I] - kr_14 * x[D]);
}

/* Propensity function 16*/
double React15(const int *x, double t, double vol, const double *data, int sd)
{
  return vol * (kf_15 * x[IL] - kr_15 * x[DL]);
}

/* Propensity function 17*/
double React16(const int *x, double t, double vol, const double *data, int sd)
{
  return vol * (kf_16 * x[ILL] - kr_16 * x[DLL]);
}


/* COLLECTION OF PROPENSITIES (STATIC CODE) */
PropensityFun *ALLOC_propensities(void)
{
  PropensityFun *ptr = malloc(sizeof(PropensityFun)*NR);

  ptr[0]=React0;
  ptr[1]=React1;
  ptr[2]=React2;
  ptr[3]=React3;
  ptr[4]=React4;
  ptr[5]=React5;
  ptr[6]=React6;
  ptr[7]=React7;
  ptr[8]=React8;
  ptr[9]=React9;
  ptr[10]=React10;
  ptr[11]=React11;
  ptr[12]=React12;
  ptr[13]=React13;
  ptr[14]=React14;
  ptr[15]=React15;
  ptr[16]=React16;

  return ptr;
}

void FREE_propensities(PropensityFun* ptr)
{
  free(ptr);
}
