#! /bin/bash
#
# execute sbml2rdme
#
# By V.Gerdin
# Brian Drawert

#############################################

if [ "$0"="-bash" -o "$0"="bash" ];then
    EXE_FILE="${BASH_SOURCE[0]}";
else
    EXE_FILE=$0
fi
if [ -L "$EXE_FILE" ]; then
MY_PATH=$(dirname $(readlink $EXE_FILE))
else
MY_PATH=$(dirname $EXE_FILE)
fi
SOURCEPATH=$MY_PATH"/src/"
TESTPATH=$MY_PATH"/test/"

#############################################

MAIN=$SOURCEPATH"sbml2rdme.py"

if [ $# -lt 1 ] || [ $# -gt 2 ]
then
  echo 'Usage: sbml2rdme <model.xml> [output directory]'
  exit 1
else
  INPUTFLAG='-f'$1
  if [ $# -eq 2 ]
  then
    OUTPUTFLAG='-o'$2
  fi
  
  #ALTER PYTHONPATH in order to find the source scripts
  export PYTHONPATH=$SOURCEPATH:"/usr/local/lib/python2.7/site-packages/":$PYTHONPATH

  echo "python $MAIN $INPUTFLAG $OUTPUTFLAG"
  python $MAIN $INPUTFLAG $OUTPUTFLAG

  exit
fi
